/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SSlugRouteImport } from './routes/s.$slug'
import { Route as RTokenRouteImport } from './routes/r.$token'
import { Route as AdminStatsRouteImport } from './routes/admin/stats'
import { Route as AdminResponsesRouteImport } from './routes/admin/responses'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminExportsRouteImport } from './routes/admin/exports'
import { Route as AdminAlertsRouteImport } from './routes/admin/alerts'
import { Route as ApiAdminExportDotcsvRouteImport } from './routes/api/admin/export[.]csv'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RTokenRoute = RTokenRouteImport.update({
  id: '/r/$token',
  path: '/r/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStatsRoute = AdminStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResponsesRoute = AdminResponsesRouteImport.update({
  id: '/responses',
  path: '/responses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExportsRoute = AdminExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlertsRoute = AdminAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAdminExportDotcsvRoute = ApiAdminExportDotcsvRouteImport.update({
  id: '/api/admin/export.csv',
  path: '/api/admin/export.csv',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/exports': typeof AdminExportsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/responses': typeof AdminResponsesRoute
  '/admin/stats': typeof AdminStatsRoute
  '/r/$token': typeof RTokenRoute
  '/s/$slug': typeof SSlugRoute
  '/api/admin/export.csv': typeof ApiAdminExportDotcsvRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/exports': typeof AdminExportsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/responses': typeof AdminResponsesRoute
  '/admin/stats': typeof AdminStatsRoute
  '/r/$token': typeof RTokenRoute
  '/s/$slug': typeof SSlugRoute
  '/api/admin/export.csv': typeof ApiAdminExportDotcsvRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/exports': typeof AdminExportsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/responses': typeof AdminResponsesRoute
  '/admin/stats': typeof AdminStatsRoute
  '/r/$token': typeof RTokenRoute
  '/s/$slug': typeof SSlugRoute
  '/api/admin/export.csv': typeof ApiAdminExportDotcsvRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/reset-password'
    | '/admin/alerts'
    | '/admin/exports'
    | '/admin/reports'
    | '/admin/responses'
    | '/admin/stats'
    | '/r/$token'
    | '/s/$slug'
    | '/api/admin/export.csv'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/reset-password'
    | '/admin/alerts'
    | '/admin/exports'
    | '/admin/reports'
    | '/admin/responses'
    | '/admin/stats'
    | '/r/$token'
    | '/s/$slug'
    | '/api/admin/export.csv'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/reset-password'
    | '/admin/alerts'
    | '/admin/exports'
    | '/admin/reports'
    | '/admin/responses'
    | '/admin/stats'
    | '/r/$token'
    | '/s/$slug'
    | '/api/admin/export.csv'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  RTokenRoute: typeof RTokenRoute
  SSlugRoute: typeof SSlugRoute
  ApiAdminExportDotcsvRoute: typeof ApiAdminExportDotcsvRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$token': {
      id: '/r/$token'
      path: '/r/$token'
      fullPath: '/r/$token'
      preLoaderRoute: typeof RTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/stats': {
      id: '/admin/stats'
      path: '/stats'
      fullPath: '/admin/stats'
      preLoaderRoute: typeof AdminStatsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/responses': {
      id: '/admin/responses'
      path: '/responses'
      fullPath: '/admin/responses'
      preLoaderRoute: typeof AdminResponsesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/exports': {
      id: '/admin/exports'
      path: '/exports'
      fullPath: '/admin/exports'
      preLoaderRoute: typeof AdminExportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/alerts': {
      id: '/admin/alerts'
      path: '/alerts'
      fullPath: '/admin/alerts'
      preLoaderRoute: typeof AdminAlertsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/admin/export.csv': {
      id: '/api/admin/export.csv'
      path: '/api/admin/export.csv'
      fullPath: '/api/admin/export.csv'
      preLoaderRoute: typeof ApiAdminExportDotcsvRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAlertsRoute: typeof AdminAlertsRoute
  AdminExportsRoute: typeof AdminExportsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminResponsesRoute: typeof AdminResponsesRoute
  AdminStatsRoute: typeof AdminStatsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAlertsRoute: AdminAlertsRoute,
  AdminExportsRoute: AdminExportsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminResponsesRoute: AdminResponsesRoute,
  AdminStatsRoute: AdminStatsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  RTokenRoute: RTokenRoute,
  SSlugRoute: SSlugRoute,
  ApiAdminExportDotcsvRoute: ApiAdminExportDotcsvRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
