// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function createSupabaseAdminClient() {
  const SUPABASE_URL = process.env.SUPABASE_URL;
  const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_SERVICE_ROLE_KEY ? ["SUPABASE_SERVICE_ROLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Configure the Supabase project environment before starting the app.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
  });
}

const clients = new Map<string, ReturnType<typeof createSupabaseAdminClient>>();
const loggedReasons = new Set<string>();

function callerFile(): string | undefined {
  const stack = new Error().stack;
  if (!stack) return undefined;
  const line = stack
    .split("\n")
    .map((entry) => entry.trim())
    .find((entry) => entry.includes("/src/") && !entry.includes("client.server.ts"));
  return line?.replace(/^at\s+/, "");
}

// Server-side Supabase client with service role - bypasses RLS.
// SECURITY: only call this from trusted server-side modules, never client code.
export function createAdminClient(reason: string): ReturnType<typeof createSupabaseAdminClient> {
  if (!reason.trim()) {
    throw new Error("createAdminClient(reason) requires a non-empty audit reason.");
  }
  const key = reason.trim();
  if (!loggedReasons.has(key)) {
    loggedReasons.add(key);
    console.log(
      JSON.stringify({
        kind: "audit.supabaseAdmin",
        reason: key,
        file: callerFile() ?? null,
        ts: new Date().toISOString(),
      }),
    );
  }
  let client = clients.get(key);
  if (!client) {
    client = createSupabaseAdminClient();
    clients.set(key, client);
  }
  return client;
}

export function __resetAdminClientAuditForTests(): void {
  clients.clear();
  loggedReasons.clear();
}
